export const siteConfig = {
  name: "Rozx",
  title: "Rozx - The Operating System for Service Businesses",
  description:
    "Appointments, CRM, payments, marketing, and custom websites. Everything your service business needs to start, run, and scale on a single unified platform.",
  url: "https://rozx.in",
  ogImage: "https://rozx.in/og/home.png",
  creator: "Rozx",
  keywords: [
    "Rozx",
    "Rozx software",
    "Rozx salon software",
    "Rozx CRM",
    "Rozx POS",
    "Rozx booking",
    "salon software",
    "spa management",
    "appointment booking",
    "service business software",
    "CRM for salons",
    "business operating system",
    "barbershop software",
    "nail studio management",
    "wellness center software",
    "beauty business software",
    "salon POS",
    "online booking system",
    "aesthetic clinic software",
    "salon billing software India",
    "GST invoicing for salons",
    "WhatsApp appointment reminders",
    "spa booking software India",
    "hair salon POS system",
    "beauty parlour management app",
    "franchise salon software",
    "queue management software",
    "booking calendar app",
  ],
  contact: {
    email: "hello@rozx.in",
    phone: "",
    address: "Rohini, New Delhi, India",
    calendly: "https://calendly.com/rozxin/30min",
  },
  social: {
    instagram: "https://www.instagram.com/rozxhq",
    linkedin: "https://www.linkedin.com/company/rozxhq",
    twitter: "https://x.com/rozxhq",
    facebook: "https://www.facebook.com/rozxhq",
    youtube: "https://www.youtube.com/@rozxhq",
    threads: "https://www.threads.net/@rozxhq",
  },
  pricing: {
    trialDays: 14,
    currency: "INR",
    currencySymbol: "₹",
    annualDiscountPercent: 20,
    plans: [
      {
        id: "starter",
        name: "Starter",
        headline: "Everything to get started",
        monthlyPrice: 999,
        annualPrice: 9599,
        popular: false,
        features: [
          "1 Branch",
          "10 Staff Members",
          "Basic Website",
          "Online Booking",
          "Customer CRM",
          "Invoicing & Billing",
          "Email Support",
        ],
      },
      {
        id: "growth",
        name: "Growth",
        headline: "Scale with confidence",
        monthlyPrice: 1999,
        annualPrice: 19199,
        popular: true,
        features: [
          "3 Branches",
          "30 Staff Members",
          "Custom Domain Website",
          "Marketing Automation",
          "Loyalty & Memberships",
          "Inventory Management",
          "WhatsApp Integration",
          "Priority Support",
        ],
      },
      {
        id: "professional",
        name: "Professional",
        headline: "Full power, zero limits",
        monthlyPrice: 2999,
        annualPrice: 28799,
        popular: false,
        features: [
          "10 Branches",
          "Unlimited Staff",
          "AI Assistant",
          "Advanced Analytics",
          "Workflow Automation",
          "API Access",
          "Custom Reports",
          "Dedicated Account Manager",
        ],
      },
      {
        id: "enterprise",
        name: "Enterprise",
        headline: "Built for your organization",
        monthlyPrice: null,
        annualPrice: null,
        popular: false,
        features: [
          "Unlimited Branches",
          "White Label",
          "Franchise Management",
          "Custom Integrations",
          "SLA Guarantee",
          "Dedicated Infrastructure",
          "On-Premise Option",
          "24/7 Premium Support",
        ],
      },
    ],
  },
} as const;

export type SiteConfig = typeof siteConfig;
