export const siteConfig = {
  name: "Rozx",
  title: "Rozx - Booking & Billing Software for Salons, Spas & Clinics",
  description:
    "Manage your appointments, billing, staff, and customer relationships with a custom website for your brand. Simple, transparent pricing for Indian service businesses.",
  url: process.env.NEXT_PUBLIC_SITE_URL || "https://rozx.in",
  ogImage: process.env.NEXT_PUBLIC_SITE_URL
    ? `${process.env.NEXT_PUBLIC_SITE_URL}/og/home.png`
    : "https://rozx.in/og/home.png",
  creator: "Rozx Team",
  keywords: [
    "Rozx",
    "Rozx software",
    "Rozx salon software",
    "Rozx CRM",
    "Rozx POS",
    "Rozx booking",
    "salon software",
    "spa management",
    "appointment booking",
    "service business software",
    "CRM for salons",
    "booking and billing software",
    "barbershop software",
    "nail studio management",
    "wellness center software",
    "beauty business software",
    "salon POS",
    "online booking system",
    "aesthetic clinic software",
    "salon billing software India",
    "GST invoicing for salons",
    "WhatsApp appointment reminders",
    "spa booking software India",
    "hair salon POS system",
    "beauty parlour management app",
    "booking calendar app",
  ],
  contact: {
    email: "hello@rozx.in",
    phone: "",
    address: "New Delhi, India",
    calendly: "",
  },
  legal: {
    entityName: "Rozx",
    contactEmail: "hello@rozx.in",
    lastUpdated: "July 21, 2026",
    governingLaw: "India",
    jurisdiction: "Courts of New Delhi, India",
  },
  social: {
    instagram: "https://www.instagram.com/rozxhq",
    linkedin: "https://www.linkedin.com/company/rozxhq",
    twitter: "https://x.com/rozxhq",
    facebook: "https://www.facebook.com/rozxhq",
    youtube: "https://www.youtube.com/@rozxhq",
    threads: "https://www.threads.net/@rozxhq",
  },
  pricing: {
    currency: "INR",
    currencySymbol: "₹",
    plans: [
      {
        id: "starter",
        name: "Starter",
        headline: "Essential booking and billing for single-outlet salons & studios.",
        monthlyPrice: 999,
        annualPrice: 9999,
        annualSavingsAmount: 1989,
        badge: null,
        limits: {
          branches: "1 Branch",
          staff: "Up to 5 Staff",
          appointments: "Unlimited Appointments",
        },
        features: [
          "1 Branch & up to 5 Staff",
          "Unlimited Appointments & Bookings",
          "Color-coded booking calendar",
          "Customer CRM & visit history",
          "WhatsApp appointment reminders",
          "GST POS & thermal billing",
          "Basic business analytics",
        ],
      },
      {
        id: "growth",
        name: "Growth",
        headline: "For expanding businesses requiring custom domain & marketing tools.",
        monthlyPrice: 1999,
        annualPrice: 19999,
        annualSavingsAmount: 3989,
        badge: "Most Popular",
        limits: {
          branches: "3 Branches",
          staff: "Up to 15 Staff",
          appointments: "Unlimited Appointments",
        },
        features: [
          "Up to 3 Branches & 15 Staff",
          "Unlimited Appointments & Bookings",
          "Everything in Starter, plus:",
          "Custom domain booking website",
          "Targeted SMS & WhatsApp marketing",
          "Staff commission management",
          "Digital intake & waiver forms",
          "Resource & room locking",
        ],
      },
      {
        id: "professional",
        name: "Professional",
        headline: "Unlimited scale and priority support for large salon chains & clinics.",
        monthlyPrice: 2999,
        annualPrice: 29999,
        annualSavingsAmount: 5989,
        badge: "Full Power",
        limits: {
          branches: "Up to 10 Branches",
          staff: "Unlimited Staff",
          appointments: "Unlimited Appointments",
        },
        features: [
          "Up to 10 Branches & Unlimited Staff",
          "Unlimited Appointments & Bookings",
          "Everything in Growth, plus:",
          "Priority customer support",
          "API & webhook access",
          "Advanced multi-branch reporting",
          "Custom onboarding & data setup",
        ],
      },
    ],
  },
} as const;

export type SiteConfig = typeof siteConfig;
